### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ematte** [ematte/text-editor-with-tabs#27]
- [ ] add saving tabs to files
- [ ] add shortcut for saving files
- [ ] add creating files
- [ ] add saving unsaved tabs and converting them to FileTabs
- [ ] add directory watcher to rescan the file tree on changes
- [ ] redo the file tree in flexbox
- [ ] refactor the text component into it's own class
